
package team.g3.delicacysearch.dao;

import org.apache.ibatis.annotations.Mapper;
import team.g3.delicacysearch.model.FoodTriple;

import java.util.List;

@Mapper
public interface FoodTripleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_triple
     *
     * @mbg.generated
     */
    int insert(FoodTriple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_triple
     *
     * @mbg.generated
     */
    List<FoodTriple> selectAll();

    List<FoodTriple> selectBySource(String cuisine);

    List<FoodTriple> selectByTarget(String target);
}