
package team.g3.delicacysearch.model;



import java.io.Serializable;

public class FoodTriple implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_triple.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_triple.relation
     *
     * @mbg.generated
     */
    private String relation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_triple.target
     *
     * @mbg.generated
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table food_triple
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_triple.source
     *
     * @return the value of food_triple.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_triple.source
     *
     * @param source the value for food_triple.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_triple.relation
     *
     * @return the value of food_triple.relation
     *
     * @mbg.generated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_triple.relation
     *
     * @param relation the value for food_triple.relation
     *
     * @mbg.generated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_triple.target
     *
     * @return the value of food_triple.target
     *
     * @mbg.generated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_triple.target
     *
     * @param target the value for food_triple.target
     *
     * @mbg.generated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_triple
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", source=").append(source);
        sb.append(", relation=").append(relation);
        sb.append(", target=").append(target);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}