package pers.spl.ziot.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import pers.spl.ziot.model.Message;

@Mapper
public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    List<Message> selectAll();
    List<Message> selectByDevice(Integer deviceId);
}