package com.java.es.dao;

import com.java.es.model.FoodTriple;
import java.util.List;

public interface FoodTripleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_triple
     *
     * @mbg.generated
     */
    int insert(FoodTriple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_triple
     *
     * @mbg.generated
     */
    List<FoodTriple> selectAll();

    List<FoodTriple> selectBySource(String cuisine);
}